[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
novahub-plugin-manager = { path = "../crates/plugin-manager" }
serde_json = "1"
sysinfo = { version = "0.38.3", default-features = false, features = ["system"] }

[lints]
workspace = true
