#![deny(unsafe_code)]

use std::path::Path;
use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};
use std::thread;
use std::time::{Duration, Instant};

use novahub_plugin_manager::{
    AuthorizedCapability, CapabilityBroker, CapabilityRequest, EffectiveGrant, HostFileHandle,
    PluginIdentity,
};
use wasmtime::{
    Cache, CacheConfig, Config, Engine, Store, StoreLimits, StoreLimitsBuilder,
    component::{Component, Linker},
};
use wasmtime_wasi::{ResourceTable, WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

/// WIT-generated Component Model bindings. WIT remains the single ABI source;
/// this module is regenerated by the compiler from `wit/novahub-plugin`.
pub mod wit {
    #![allow(unsafe_code, unused_variables)]

    // Keep the generated host imports and plugin exports sourced from this
    // single WIT package; capability calls must not grow a parallel ABI.
    wasmtime::component::bindgen!({
        world: "plugin",
        path: "../../wit/novahub-plugin",
    });
}

#[derive(Debug)]
pub enum ComponentError {
    Configuration(String),
    Compile(String),
    Instantiate(String),
    Resource(String),
    Plugin(String),
}

impl std::fmt::Display for ComponentError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Configuration(error) => write!(f, "runtime configuration failed: {error}"),
            Self::Compile(error) => write!(f, "component compilation failed: {error}"),
            Self::Instantiate(error) => write!(f, "component instantiation failed: {error}"),
            Self::Resource(error) => write!(f, "component resource limit failed: {error}"),
            Self::Plugin(error) => write!(f, "plugin call failed: {error}"),
        }
    }
}

impl std::error::Error for ComponentError {}

struct RuntimeState {
    limits: StoreLimits,
    wasi: WasiCtx,
    table: ResourceTable,
    broker: CapabilityBroker,
    identity: PluginIdentity,
    grant: EffectiveGrant,
    capability_adapter: Arc<dyn CapabilityAdapter>,
}

/// Result returned by a host-owned capability adapter.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CapabilityValue {
    Unit,
    Text(String),
    Bytes(Vec<u8>),
}

/// Runtime-neutral boundary between WIT imports and the owning host process.
///
/// The runtime performs the local grant check first. Implementations must
/// still revalidate the identity and current grant at the authoritative host
/// boundary because a sibling Plugin Host is not the permission owner.
pub trait CapabilityAdapter: Send + Sync {
    /// Performs one already normalized capability operation.
    ///
    /// # Errors
    ///
    /// Returns a bounded host error when the operation is denied, unsupported,
    /// or fails at the platform boundary.
    fn call(
        &self,
        identity: &PluginIdentity,
        capability: AuthorizedCapability,
        payload: Option<&str>,
    ) -> Result<CapabilityValue, String>;
}

#[derive(Default)]
struct UnavailableCapabilityAdapter;

impl CapabilityAdapter for UnavailableCapabilityAdapter {
    fn call(
        &self,
        _identity: &PluginIdentity,
        capability: AuthorizedCapability,
        _payload: Option<&str>,
    ) -> Result<CapabilityValue, String> {
        let message = match capability {
            AuthorizedCapability::ClipboardRead | AuthorizedCapability::ClipboardWrite => {
                "clipboard capability adapter is unavailable"
            }
            AuthorizedCapability::FilesSelect => "file picker capability adapter is unavailable",
            AuthorizedCapability::Http { .. } => "HTTP capability adapter is unavailable",
            AuthorizedCapability::StorageWrite { .. }
            | AuthorizedCapability::StoragePut { .. }
            | AuthorizedCapability::StorageGet { .. } => {
                "storage capability adapter is unavailable"
            }
            AuthorizedCapability::FilesRead { .. } | AuthorizedCapability::FilesWrite { .. } => {
                "file capability adapter is unavailable"
            }
            AuthorizedCapability::Logging => "logging capability adapter is unavailable",
            AuthorizedCapability::Notification => "notification capability adapter is unavailable",
        };
        Err(message.into())
    }
}

impl wit::novahub::plugin::types::Host for RuntimeState {}

impl wit::novahub::plugin::capabilities::Host for RuntimeState {
    fn read_clipboard(&mut self) -> Result<String, String> {
        match self.call_capability(CapabilityRequest::ClipboardRead, None)? {
            CapabilityValue::Text(value) => Ok(value),
            CapabilityValue::Unit | CapabilityValue::Bytes(_) => {
                Err("clipboard adapter returned no text".into())
            }
        }
    }

    fn write_clipboard(&mut self, value: String) -> Result<(), String> {
        self.expect_unit(CapabilityRequest::ClipboardWrite, Some(&value))
    }

    fn pick_file(&mut self) -> Result<Option<String>, String> {
        match self.call_capability(CapabilityRequest::FilesSelect, None)? {
            CapabilityValue::Unit => Ok(None),
            CapabilityValue::Text(token) => Ok(Some(token)),
            CapabilityValue::Bytes(_) => Err("file picker returned an unexpected value".into()),
        }
    }

    fn http_get(&mut self, url: String) -> Result<String, String> {
        match self.call_capability(
            CapabilityRequest::Http {
                origin: url.clone(),
            },
            Some(&url),
        )? {
            CapabilityValue::Text(value) => Ok(value),
            CapabilityValue::Unit | CapabilityValue::Bytes(_) => {
                Err("HTTP adapter returned no response body".into())
            }
        }
    }

    fn read_file(&mut self, token: String) -> Result<String, String> {
        match self.call_capability(
            CapabilityRequest::FilesRead {
                handle: HostFileHandle::issue(
                    self.identity.plugin_id(),
                    self.identity.session_id(),
                    &token,
                ),
            },
            Some(&token),
        )? {
            CapabilityValue::Text(value) => Ok(value),
            CapabilityValue::Unit | CapabilityValue::Bytes(_) => {
                Err("file adapter returned no text".into())
            }
        }
    }

    fn storage_write(&mut self, total_bytes: u64) -> Result<(), String> {
        self.expect_unit(CapabilityRequest::StorageWrite { total_bytes }, None)
    }

    fn storage_put(&mut self, key: String, value: Vec<u8>) -> Result<(), String> {
        self.expect_unit(CapabilityRequest::StoragePut { key, value }, None)
    }

    fn storage_get(&mut self, key: String) -> Result<Vec<u8>, String> {
        match self.call_capability(CapabilityRequest::StorageGet { key }, None)? {
            CapabilityValue::Bytes(value) => Ok(value),
            CapabilityValue::Unit | CapabilityValue::Text(_) => {
                Err("storage adapter returned an unexpected value".into())
            }
        }
    }
}

impl RuntimeState {
    fn call_capability(
        &self,
        request: CapabilityRequest,
        payload: Option<&str>,
    ) -> Result<CapabilityValue, String> {
        let authorized = self
            .broker
            .authorize(&self.identity, &self.grant, request)
            .map_err(|error| error.to_string())?;
        self.capability_adapter
            .call(&self.identity, authorized, payload)
    }

    fn expect_unit(&self, request: CapabilityRequest, payload: Option<&str>) -> Result<(), String> {
        match self.call_capability(request, payload)? {
            CapabilityValue::Unit => Ok(()),
            CapabilityValue::Text(_) | CapabilityValue::Bytes(_) => {
                Err("capability adapter returned an unexpected value".into())
            }
        }
    }
}

impl WasiView for RuntimeState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// Host-owned Wasmtime Component runtime. The Engine is shared across plugin
/// sessions; each session gets an independent Store and resource limiter.
pub struct ComponentRuntime {
    engine: Engine,
    limits: ResourceLimits,
}

pub struct LoadedComponent {
    component: Component,
    runtime: Arc<ComponentRuntime>,
}

pub struct ComponentSession {
    store: Store<RuntimeState>,
    instance: wit::Plugin,
    runtime: Arc<ComponentRuntime>,
}

const COMPILED_CACHE_FILE_SOFT_LIMIT: u64 = 256;
const COMPILED_CACHE_BYTE_SOFT_LIMIT: u64 = 128 * 1024 * 1024;

impl ComponentRuntime {
    /// Creates an engine with deterministic compute and memory controls.
    ///
    /// # Errors
    ///
    /// Returns a configuration error when Wasmtime rejects the requested
    /// resource controls.
    pub fn new(limits: ResourceLimits) -> Result<Arc<Self>, ComponentError> {
        Self::new_with_optional_cache(limits, None)
    }

    /// Creates an engine backed by Wasmtime's content-addressed compilation
    /// cache. The cache remains bounded and does not change the Component ABI.
    ///
    /// # Errors
    ///
    /// Returns a configuration error when the cache directory or Wasmtime
    /// engine configuration is invalid.
    pub fn new_with_cache(
        limits: ResourceLimits,
        cache_directory: &Path,
    ) -> Result<Arc<Self>, ComponentError> {
        Self::new_with_optional_cache(limits, Some(cache_directory))
    }

    fn new_with_optional_cache(
        limits: ResourceLimits,
        cache_directory: Option<&Path>,
    ) -> Result<Arc<Self>, ComponentError> {
        let mut config = Config::new();
        config
            .wasm_component_model(true)
            .consume_fuel(true)
            .epoch_interruption(true);
        if let Some(cache_directory) = cache_directory {
            let mut cache_config = CacheConfig::new();
            cache_config
                .with_directory(cache_directory)
                .with_file_count_soft_limit(COMPILED_CACHE_FILE_SOFT_LIMIT)
                .with_files_total_size_soft_limit(COMPILED_CACHE_BYTE_SOFT_LIMIT);
            let cache = Cache::new(cache_config)
                .map_err(|error| ComponentError::Configuration(error.to_string()))?;
            config.cache(Some(cache));
        }
        let engine = Engine::new(&config)
            .map_err(|error| ComponentError::Configuration(error.to_string()))?;
        Ok(Arc::new(Self { engine, limits }))
    }

    /// Compiles a Component without instantiating or running plugin code.
    ///
    /// # Errors
    ///
    /// Returns [`ComponentError::Compile`] when the bytes are not a valid
    /// Component for this runtime.
    pub fn load(self: &Arc<Self>, bytes: &[u8]) -> Result<LoadedComponent, ComponentError> {
        let component = Component::from_binary(&self.engine, bytes)
            .map_err(|error| ComponentError::Compile(error.to_string()))?;
        Ok(LoadedComponent {
            component,
            runtime: Arc::clone(self),
        })
    }

    fn new_store(
        &self,
        identity: PluginIdentity,
        grant: EffectiveGrant,
        capability_adapter: Arc<dyn CapabilityAdapter>,
    ) -> Result<Store<RuntimeState>, ComponentError> {
        let memory = usize::try_from(self.limits.max_memory_bytes).map_err(|_| {
            ComponentError::Resource("memory limit does not fit the host usize".into())
        })?;
        let limits = StoreLimitsBuilder::new()
            .memory_size(memory)
            .instances(8)
            .tables(8)
            .build();
        let wasi = WasiCtxBuilder::new().build();
        let mut store = Store::new(
            &self.engine,
            RuntimeState {
                limits,
                wasi,
                table: ResourceTable::new(),
                broker: CapabilityBroker,
                identity,
                grant,
                capability_adapter,
            },
        );
        store.limiter(|state| &mut state.limits);
        store
            .set_fuel(self.limits.max_fuel)
            .map_err(|error| ComponentError::Resource(error.to_string()))?;
        store.set_epoch_deadline(1);
        Ok(store)
    }
}

impl LoadedComponent {
    /// Instantiates a component and runs its required `initialize` export.
    ///
    /// # Errors
    ///
    /// Returns an instantiation or plugin error when linking, initialization,
    /// or Store resource setup fails.
    pub fn instantiate(&self) -> Result<ComponentSession, ComponentError> {
        self.instantiate_with_context(
            PluginIdentity::new("unbound", "unbound"),
            EffectiveGrant::default(),
        )
    }

    /// Instantiates a component with the identity and effective permissions
    /// used by imported host capabilities.
    ///
    /// # Errors
    ///
    /// Returns an instantiation or plugin error when linking, initialization,
    /// or Store resource setup fails.
    pub fn instantiate_with_context(
        &self,
        identity: PluginIdentity,
        grant: EffectiveGrant,
    ) -> Result<ComponentSession, ComponentError> {
        self.instantiate_with_adapter(identity, grant, Arc::new(UnavailableCapabilityAdapter))
    }

    /// Instantiates a component with an explicit host-owned capability adapter.
    ///
    /// # Errors
    ///
    /// Returns an instantiation or plugin error when linking, initialization,
    /// or Store resource setup fails.
    pub fn instantiate_with_adapter(
        &self,
        identity: PluginIdentity,
        grant: EffectiveGrant,
        capability_adapter: Arc<dyn CapabilityAdapter>,
    ) -> Result<ComponentSession, ComponentError> {
        let mut store = self
            .runtime
            .new_store(identity, grant, capability_adapter)?;
        let mut linker = Linker::new(&self.runtime.engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|error| ComponentError::Instantiate(error.to_string()))?;
        wit::Plugin::add_to_linker::<_, wasmtime::component::HasSelf<RuntimeState>>(
            &mut linker,
            |state| state,
        )
        .map_err(|error| ComponentError::Instantiate(error.to_string()))?;
        let instance = wit::Plugin::instantiate(&mut store, &self.component, &linker)
            .map_err(|error| ComponentError::Instantiate(error.to_string()))?;
        let result = instance
            .call_initialize(&mut store)
            .map_err(|error| ComponentError::Plugin(error.to_string()))?;
        result.map_err(ComponentError::Plugin)?;
        Ok(ComponentSession {
            store,
            instance,
            runtime: Arc::clone(&self.runtime),
        })
    }
}

impl ComponentSession {
    /// Calls the WIT `open-view` export and returns the generated View value.
    ///
    /// # Errors
    ///
    /// Returns [`ComponentError::Plugin`] when the component traps or returns
    /// a plugin-level error.
    pub fn open(&mut self) -> Result<wit::View, ComponentError> {
        self.with_epoch_deadline(|session| {
            let result = session
                .instance
                .call_open_view(&mut session.store)
                .map_err(|error| ComponentError::Plugin(error.to_string()))?;
            result.map_err(ComponentError::Plugin)
        })
    }

    /// Calls the WIT `update` export with a bounded input string.
    ///
    /// # Errors
    ///
    /// Returns a resource error when the input exceeds the bound, or a plugin
    /// error when the component traps or returns an error.
    pub fn update(&mut self, input: &str) -> Result<wit::View, ComponentError> {
        if input.len() > MAX_PLUGIN_INPUT_BYTES {
            return Err(ComponentError::Resource(
                "plugin input exceeds the host limit".into(),
            ));
        }
        self.with_epoch_deadline(|session| {
            let result = session
                .instance
                .call_update(&mut session.store, input)
                .map_err(|error| ComponentError::Plugin(error.to_string()))?;
            result.map_err(ComponentError::Plugin)
        })
    }

    /// Executes one bounded command without creating a persistent View session.
    /// The caller owns the session and must drop it after this result returns.
    ///
    /// # Errors
    ///
    /// Returns a resource error when command or input text exceeds the host
    /// limit, or a plugin error when the Component traps or rejects the call.
    pub fn run(
        &mut self,
        command_id: &str,
        input: &str,
    ) -> Result<wit::CommandResult, ComponentError> {
        if command_id.len() > MAX_PLUGIN_INPUT_BYTES || input.len() > MAX_PLUGIN_INPUT_BYTES {
            return Err(ComponentError::Resource(
                "one-shot command input exceeds the host limit".into(),
            ));
        }
        let context = wit::CommandContext {
            command_id: command_id.to_owned(),
            input: input.to_owned(),
        };
        self.with_epoch_deadline(|session| {
            let result = session
                .instance
                .call_run(&mut session.store, &context)
                .map_err(|error| ComponentError::Plugin(error.to_string()))?;
            result.map_err(ComponentError::Plugin)
        })
    }

    /// Calls the WIT `close-plugin` export and releases the Store afterwards.
    ///
    /// # Errors
    ///
    /// Returns [`ComponentError::Plugin`] when the close export traps.
    pub fn close(mut self) -> Result<(), ComponentError> {
        self.with_epoch_deadline(|session| {
            session
                .instance
                .call_close_plugin(&mut session.store)
                .map_err(|error| ComponentError::Plugin(error.to_string()))
        })
    }

    fn with_epoch_deadline<T>(
        &mut self,
        call: impl FnOnce(&mut Self) -> Result<T, ComponentError>,
    ) -> Result<T, ComponentError> {
        let stopped = Arc::new(AtomicBool::new(false));
        let stopped_for_timer = Arc::clone(&stopped);
        let engine = self.runtime.engine.clone();
        let deadline = self.runtime.limits.compute_deadline;
        let timer = thread::spawn(move || {
            let tick = Duration::from_millis(5);
            let started = Instant::now();
            while !stopped_for_timer.load(Ordering::Relaxed) {
                if started.elapsed() >= deadline {
                    engine.increment_epoch();
                    break;
                }
                thread::sleep(tick.min(deadline.saturating_sub(started.elapsed())));
            }
        });
        let result = call(self);
        stopped.store(true, Ordering::Relaxed);
        let _ = timer.join();
        result
    }
}

pub const MAX_PLUGIN_INPUT_BYTES: usize = 1 << 20;

pub const DEFAULT_LINEAR_MEMORY_BYTES: u64 = 64 * 1024 * 1024;
pub const DEFAULT_COMPUTE_DEADLINE: Duration = Duration::from_secs(2);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceError {
    MemoryLimit,
    FuelExhausted,
    DeadlineExceeded,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ResourceLimits {
    pub max_memory_bytes: u64,
    pub max_fuel: u64,
    pub compute_deadline: Duration,
}

impl Default for ResourceLimits {
    fn default() -> Self {
        Self {
            max_memory_bytes: DEFAULT_LINEAR_MEMORY_BYTES,
            max_fuel: 10_000_000,
            compute_deadline: DEFAULT_COMPUTE_DEADLINE,
        }
    }
}

#[derive(Debug)]
pub struct ResourceBudget {
    limits: ResourceLimits,
    started_at: Instant,
    memory_bytes: u64,
    fuel_remaining: u64,
}

impl ResourceBudget {
    #[must_use]
    pub fn new(limits: ResourceLimits) -> Self {
        Self {
            fuel_remaining: limits.max_fuel,
            limits,
            started_at: Instant::now(),
            memory_bytes: 0,
        }
    }

    /// Charges linear memory against the per-plugin limit.
    ///
    /// # Errors
    ///
    /// Returns `MemoryLimit` when the requested allocation exceeds the limit.
    pub fn charge_memory(&mut self, bytes: u64) -> Result<(), ResourceError> {
        let next = self.memory_bytes.saturating_add(bytes);
        if next > self.limits.max_memory_bytes {
            return Err(ResourceError::MemoryLimit);
        }
        self.memory_bytes = next;
        Ok(())
    }

    /// Charges deterministic compute fuel and checks the wall-clock deadline.
    ///
    /// # Errors
    ///
    /// Returns `FuelExhausted` or `DeadlineExceeded` when a budget is crossed.
    pub fn consume_fuel(&mut self, amount: u64) -> Result<(), ResourceError> {
        if self.started_at.elapsed() > self.limits.compute_deadline {
            return Err(ResourceError::DeadlineExceeded);
        }
        if amount > self.fuel_remaining {
            return Err(ResourceError::FuelExhausted);
        }
        self.fuel_remaining -= amount;
        Ok(())
    }

    #[must_use]
    pub const fn memory_bytes(&self) -> u64 {
        self.memory_bytes
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SessionId(String);

impl SessionId {
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SessionError {
    StaleRevision,
    Closed,
}

impl SessionError {
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::StaleRevision => "stale_revision",
            Self::Closed => "session_closed",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PluginSession {
    id: SessionId,
    revision: u64,
    closed: bool,
}

impl PluginSession {
    #[must_use]
    pub fn open(id: SessionId) -> Self {
        Self {
            id,
            revision: 1,
            closed: false,
        }
    }

    #[must_use]
    pub const fn revision(&self) -> u64 {
        self.revision
    }

    #[must_use]
    pub fn id(&self) -> &SessionId {
        &self.id
    }

    /// Applies one event only when it targets the current revision.
    ///
    /// # Errors
    ///
    /// Returns `Closed` after close, or `StaleRevision` for an old event.
    pub fn update(&mut self, expected_revision: u64) -> Result<u64, SessionError> {
        if self.closed {
            return Err(SessionError::Closed);
        }
        if expected_revision != self.revision {
            return Err(SessionError::StaleRevision);
        }
        self.revision = self.revision.saturating_add(1);
        Ok(self.revision)
    }

    pub fn close(&mut self) {
        self.closed = true;
    }
}

#[cfg(test)]
mod tests {
    use super::{PluginSession, SessionError, SessionId};

    fn runtime_state(grant: novahub_plugin_manager::EffectiveGrant) -> super::RuntimeState {
        super::RuntimeState {
            limits: wasmtime::StoreLimitsBuilder::new().build(),
            wasi: wasmtime_wasi::WasiCtxBuilder::new().build(),
            table: wasmtime_wasi::ResourceTable::new(),
            broker: novahub_plugin_manager::CapabilityBroker,
            identity: novahub_plugin_manager::PluginIdentity::new("demo", "session-1"),
            grant,
            capability_adapter: std::sync::Arc::new(super::UnavailableCapabilityAdapter),
        }
    }

    #[test]
    fn session_rejects_stale_revision_and_accepts_monotonic_updates() {
        let mut session = PluginSession::open(SessionId::new("demo"));
        assert_eq!(session.revision(), 1);
        session.update(1).expect("first revision is current");
        assert_eq!(session.revision(), 2);
        assert_eq!(session.update(1), Err(SessionError::StaleRevision));
    }

    #[test]
    fn closed_session_rejects_updates() {
        let mut session = PluginSession::open(SessionId::new("demo"));
        session.close();
        assert_eq!(session.update(1), Err(SessionError::Closed));
    }

    #[test]
    fn resource_budget_enforces_memory_and_fuel_limits() {
        let limits = super::ResourceLimits {
            max_memory_bytes: 8,
            max_fuel: 3,
            compute_deadline: std::time::Duration::from_secs(2),
        };
        let mut budget = super::ResourceBudget::new(limits);
        budget.charge_memory(8).expect("within memory limit");
        assert_eq!(
            budget.charge_memory(1),
            Err(super::ResourceError::MemoryLimit)
        );
        budget.consume_fuel(3).expect("within fuel limit");
        assert_eq!(
            budget.consume_fuel(1),
            Err(super::ResourceError::FuelExhausted)
        );
    }

    #[test]
    fn generated_capability_imports_default_to_broker_denial() {
        let mut state = runtime_state(novahub_plugin_manager::EffectiveGrant::default());
        let error = super::wit::novahub::plugin::capabilities::Host::read_clipboard(&mut state)
            .expect_err("empty effective grant must be denied");
        assert_eq!(error, "capability not granted");
    }

    #[test]
    fn granted_capability_reaches_only_the_explicit_adapter_boundary() {
        let manifest = novahub_plugin_manager::PluginManifest::new("demo", "1.0.0", ">=1.0, <2.0")
            .with_permissions(["clipboard"]);
        let declared = manifest.declared_permissions();
        let grant =
            novahub_plugin_manager::EffectiveGrant::from_layers(declared, declared, declared);
        let mut state = runtime_state(grant);
        let error = super::wit::novahub::plugin::capabilities::Host::read_clipboard(&mut state)
            .expect_err("native adapter is intentionally not implemented in Plugin Host");
        assert_eq!(error, "clipboard capability adapter is unavailable");
    }
}
