[package]
name = "novahub-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
novahub-migration = { path = "../../crates/migration" }
novahub-plugin-manager = { path = "../../crates/plugin-manager" }
novahub-storage = { path = "../../crates/storage" }
serde_json = "1"

[lints]
workspace = true
