[package]
name = "novahub-plugin-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ring = "0.17.14"
sha2 = "0.10.9"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8.23"
zip = { version = "4.6.1", default-features = false, features = ["deflate-flate2-zlib-rs"] }

[dependencies.wasmparser]
version = "0.252.0"
default-features = false
features = ["std", "validate", "component-model"]

[lints]
workspace = true
